name: Generate Markdown List

on:
  push:
    branches:
      - main  # Cambia a la rama que prefieras

jobs:
  generate-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml pandas

      - name: Generate markdown files list
        run: |
          python generate_markdown_list.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add markdown_files.yaml markdown_files.json markdown_files.csv
          git commit -m 'Generate markdown files list'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
